import { useEffect, useState } from 'react'
import { api } from './api/token'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { data } from './types/types'
import { Navbar } from './components/Navbar'
import { Languages } from './components/Languages'

const Home: NextPage = () => {
  const [streams, setStreams] = useState<data[]>([])
  const [language, setLanguage] = useState<string>('')

  useEffect(() => {
    const getData = async () => {
        const result = await api.get(`https://api.twitch.tv/helix/streams?${language}`)

        const dataArray: data[] = result.data.data
        const updatedArray = dataArray.map(stream => {
          const newUrl = stream.thumbnail_url.replace('{width}', '370').replace('{height}', '208')
          stream.thumbnail_url = newUrl  

          let newTitle
              if (stream.title.length > 26) {
                newTitle = stream.title.slice(0, 27)
                newTitle += '...'
              } else {
                return stream.title
              }
            stream.title = newTitle
        })

        setStreams(result.data.data)
      }
      getData()
    }, [language])
 console.log(streams)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
  
      <div className='containerMain'>
        <h1 className='PopStreams'>Most Popular streams</h1>
        <Languages setLanguage={setLanguage}/>
        
        <div className='streams'>
          {streams.map(item => (
            <div className='streams-divs'>
              <a href={`http://twitch.tv/${item.user_name}`} target={'_blank'}>
                <img className={styles.img} src={item.thumbnail_url} alt="" />
              </a>
              <div className='viewer-live'>
                <p className='live'>LIVE</p>
                <p className='viewers'>{item.viewer_count} viewers</p>
              </div>

              <div className='streamerInfo'>
                <h3 className='titles'>{item.title}</h3>

                <a href={`/search/${item.user_name}`}>
                  <h1 className='names userName'>
                    {item.user_name}
                  </h1>
                </a>
                <h3 className='names gameName'>{item.game_name}</h3>
              </div>
            </div>
          ))}
        </div>
      </div>
      
    </div>
  )
}

export default Home